name: 'Sovy - Amazon SES Sync Action'
description: 'Upload email templates from within a Github repo to Amazon SES'
inputs:
  templates_dir:
    description: 'A path to a directory where your email templates are stored'
    required: true
  token:
    description: 'A Sovy Github Sync Token generated inside the https://sovy.app dashboard'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'mail'
  color: 'yellow'
